### PR TITLE
Docker scheduled tests update

### PR DESCRIPTION
**Pull request by passalis**
This PR updates the version of the image currently used in scheduled tests.

Currently, the tests fail since we are no longer have images tagged as `cpu_latest`:

`docker: Error response from daemon: manifest for opendr/opendr-toolkit:cpu_latest not found: manifest unknown: manifest unknown.`

This PR updates the docker image used to the latest available version.

### CODE REVIEW

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Comment by stefaniapedrazzi** [comment]
@passalis I also updated the installation documentation.
Please tell if it is ok that I will accept again this PR.

@ad-daniel could you review it too?

**Comment by passalis** [comment]
> @passalis I also updated the installation documentation. Please tell me if it is ok that I will accept again this PR.

Yes, it is fine! Thank you!

**Review by stefaniapedrazzi — APPROVED** [review]

**Review by ad-daniel — APPROVED** [review]
Thank you

**Pull request merged**
