### PR TITLE
Lightweight openpose fixes

### LINKED ISSUE #36: Lightweight OpenPose optimize fails to run if num_refinement_stages != 2
On [this](https://github.com/tasostefas/opendr_internal/blob/2f6d15fab31ddb3c604f0bd6a2a7e8689904e051/src/perception/pose_estimation/lightweight_open_pose/lightweight_open_pose_learner.py#L847) line, the naming of the outputs requires `num_refinement_stages` to be set to the default value of 2, setting it to another value makes the `optimze` method to fail to run.

[Here](https://github.com/tasostefas/opendr_internal/blob/2f6d15fab31ddb3c604f0bd6a2a7e8689904e051/src/perception/pose_estimation/lightweight_open_pose/lightweight_open_pose_learner.py#L844) the names need to be set dynamically according to `num_refinement_stages`.

### PR DESCRIPTION
**Pull request by tsampazk**
- Fixed height check on transformations.py according to [original lightweight open pose repo #202.](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/pull/202)
- Fixes #36 
- Fixes a similar bug to the above, when using half precision and then trying to optimize the model with onnx

(Please add any appropriate tags missing)

### CODE REVIEW

**Review by ad-daniel — DISMISSED** [review]
Thank you!
I think it warrants a mention in the changelog.

**Comment by tsampazk** [comment]
> Thank you! I think it warrants a mention in the changelog.

I entirely missed the changelog! Should i add something similar to this PR's description in three bullets in the bugfixes section of the changelog and commit it through this PR?

**Comment by ad-daniel** [comment]
You should add just a short summary (1 phrase or 2 maximum) and at the end link this PR itself as is done on the other examples present there already. If people need more details they can use that link to reach this page and read more about it

Yes, you add the change to the CHANGELOG file and commit it in this same PR

**Review by passalis — APPROVED** [review]
Thank you!

**Review by ad-daniel — APPROVED** [review]
Thank you!

**Pull request merged**
