### PR TITLE
skeleton-based HAR demo bug fixed

### PR DESCRIPTION
**Pull request by negarhdr**
This PR fixes the bug of the skeleton_based_human_action_recognition demo, which is mentioned in #259 yesterday. 
The demo used to work before, and this bug is created due to the last changes that I've mistakenly made in the learners recently. Now it should work without any problem. It's better to double-check. 

The branch is on top of the master branch!

### CODE REVIEW

**Review by passalis — COMMENTED** [review]
Thank you! Seems fine and fixes the issue mentioned in #259.

Can you also confirm that the code correctly handles cases where we do not find any skeleton in the first frame?

It seems that in  https://github.com/opendr-eu/opendr/blob/master/projects/perception/skeleton_based_action_recognition/demos/demo.py#L205 we need to perhaps include l. 208-211 inside `if counter > 0:`. Otherwise, ` skeleton_seq` will be undefined.

**Comment by passalis** [comment]
> It seems that in https://github.com/opendr-eu/opendr/blob/master/projects/perception/skeleton_based_action_recognition/demos/demo.py#L205 we need to perhaps include l. 208-211 inside `if counter > 0:`. Otherwise, ` skeleton_seq` will be undefined.

I have fixed this. Please check it and feel free to revert if this is not correct.

**Review by ad-daniel — APPROVED** [review]
Thank you. I've taken the opportunity to fix cppcheck since it was recently upgraded on macos

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
