### PR TITLE
Fix evaluation and data pre-processing in EfficientPS

### PR DESCRIPTION
**Pull request by vniclas**
This PR fixes a couple of issues that have been detected while preparing D8.1:
- fixing the data pre-processing for both KITTI and Cityscapes
- fixing evaluation on the KITTI dataset by introducing specific configuration files

### CODE REVIEW

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Thank you, I think a mention in the changelog is warranted. 
Also I don't believe `self.config_file` is ever initialized

**Comment by vniclas** [comment]
Updates:
- Fixed the PEP8 error that caused the linter to fail
- Added the bug fixes to the changelog

The config file is actually being initialized, see line 117 `self._cfg = Config.fromfile(config_file)`.

**Comment by ad-daniel** [comment]
Ah yea, my bad. Concerning the failing cppcheck you need to apply this same fix: https://github.com/opendr-eu/opendr/pull/201/commits/bcdb7b5acb46fe3242274adabec313de1f91d11d (we applied it on develop but hasn't reached master yet, so this is a good chance to do it)

**Comment by ad-daniel** [comment]
Forgot to say you need remove the space between: `& key`

**Review by ad-daniel — DISMISSED** [review]
Thank you!
What do you mean? You don't need to rely on the CI, you can also do the check locally with `python -m unittest discover -s tests/sources/` or use addons (like for visualstudio/atom) that do the formatting automatically on save

**Comment by vniclas** [comment]
Thanks for approving.

Of course, you can set up these things but it would be much more developer-friendly if this is being taken care of automatically and in the same manner for every contributor. I've been using the [pre-commit](https://pre-commit.com/) framework in a few other multi-people projects and it simplifies life a lot.
Anyway, I just wanted to draw attention to such tools in case people weren't aware. :)

**Comment by ad-daniel** [comment]
> Anyway, I just wanted to draw attention to such tools in case people weren't aware. :)

Well, I'm one of them, looks quite nice indeed, will look into it!

**Comment by vniclas** [comment]
Sorry to bother you again @ad-daniel 
I just saw a typo in the changelog file and had to fix it.

**Review by ad-daniel — APPROVED** [review]

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
