### PR TITLE
Fix 3d Tests Release

### PR DESCRIPTION
**Pull request by iliiliiliili**
Checking how to reproduce and fix the 3D tests on GH CI

### CODE REVIEW

**Comment by ad-daniel** [comment]
@iliiliiliili I have fixed the workflow, now it starts and it shows the problem I mentioned

**Comment by iliiliiliili** [comment]
@stefaniapedrazzi Is there any update on the tests not running issue?

**Comment by stefaniapedrazzi** [comment]
I started to check but unfortunately I didn't have enough time to debug it properly yet.

**Comment by stefaniapedrazzi** [comment]
I progressed solving the tests issues.
Test tools and test separate wheel should now work correctly.
There should be still issues with the wheel test and docker but if I'm not wrong you should be able to continue working on this on the separate wheel tests, is it correct?

**Comment by passalis** [comment]
@iliiliiliili Should we close this PR now or do we need an update?

**Comment by passalis** [comment]
I am closing this PR as stale. We can re-open it if needed.

**Pull request closed without merging**
