### PR TITLE
merge `master` into `develop`

### PR DESCRIPTION
**Pull request by passalis**
Propagates the fixes to develop.

No conflicts

### CODE REVIEW

**Review by ad-daniel — DISMISSED** [review]

**Review by stefaniapedrazzi — DISMISSED** [review]
Thank you

**Comment by passalis** [comment]
I also included the changes from #315

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you

**Review by ad-daniel — APPROVED** [review]
Thank you

**Pull request merged**
