### PR TITLE
Prepare v2.2.0

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Update version 
* [x] changelog
* [x] workflows
* [x] documentation
* [x] ros/ros2

Fix tests:
* [x] Test wheel: avoid version mismatch by first searching for local wheel packages
* [x] Docker build and test "no space left on device" error: use "free-disk-space" action
* [x] Docker tests:
    * [x] `perception/object_tracking_2d` fails, it seems to be due to excessive memory use in the CI/Docker test (locally works fine):
        reduce `batch_size` to 2
    * [x] `control/multi_object_search` fails because it requires CUDA: test is disabled

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Action creating the Docker is running out of space.
We could probably overcome this by creating different Docker files for the ROS and ROS2 API (to be checked).

**Comment by stefaniapedrazzi** [comment]
Finally all the enabled tests are passing:
https://github.com/opendr-eu/opendr/actions/runs/5401784419

They have now been restarted when adding the `test sources` label needed to trigger the tests that otherwise will block the merge.

**Comment by stefaniapedrazzi** [comment]
This PR is now ready for review.
Then when merged, I will release the new version of the toolkit.

**Review by passalis — APPROVED** [review]
Thank you!

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
