### PR TITLE
Merge `master` into `develop`

### PR DESCRIPTION
**Pull request by ad-daniel**
No conflicts.

### CODE REVIEW

**Review by tsampazk — APPROVED** [review]

**Comment by ad-daniel** [comment]
@passalis @Pavlos-Tosidis may I ask you to review this PR and this one https://github.com/opendr-eu/opendr/pull/397 ? 
That way I can proceed with merging develop into master and do the necessary changes in order to create releases for ROS2 as well. Thank you

**Review by Pavlos-Tosidis — APPROVED** [review]
Looks good

**Comment by ad-daniel** [comment]
uhm.. the test sources auto-cancels itself on ubuntu 18 for some reason :confused:

**Comment by ad-daniel** [comment]
It looks like the ubuntu-18 image was deprecated. In theory it should've been discontinued last month already, but I guess they kept it running longer. I've removed it from the workflow

**Review by passalis — APPROVED** [review]
Thank you!

**Review by Pavlos-Tosidis — APPROVED** [review]
Seems good

**Pull request merged**
