### PR TITLE
Refactoring: pythonic joins in test_clang_format.py/test_cppcheck.py

### PR DESCRIPTION
**Pull request by tosemml**
These slight code adjustments aim to enhance Pythonic quality by incorporating the str.join function.

### CODE REVIEW

**Comment by omichel** [comment]
It seems that the test-sources are taking forever, do you know why?

**Comment by tsampazk** [comment]
Thanks @tosemml for the improvement! It seems that there are some pep8 indentation issues in the code you modified according to the tests. 

> It seems that the test-sources are taking forever, do you know why?

The label was actually missing, i added it and approved the run.

**Review by omichel — APPROVED** [review]
Thank you.

**Review by tsampazk — APPROVED** [review]
Thanks @tosemml !

**Pull request merged**
