### PR TITLE
Prepare v3.0.0 Release

### PR DESCRIPTION
**Pull request by passalis**
This aims to prepare v3.0.0 release.

### CODE REVIEW

**Comment by passalis** [comment]
Only nine failures, that actually sounds very promising :laughing:

**Comment by passalis** [comment]
This is now stable. We wait for all features to be included in v3.0.0 to be merged and then we can continue from there.

**Comment by passalis** [comment]
Let's see if this still works...

**Comment by passalis** [comment]
The failure seems to be related to the artifacts being deleted before GEM test run. Not sure why this happened, but now it seems to work. Let's wait for develop to be merged and then see if this happens again...

**Review by omichel — DISMISSED** [review]
That looks all good to me.
We just need to set the release date in the CHANGELOG.md.

**Pull request merged**
