### PR TITLE
New Feature: Continual SLAM

### PR DESCRIPTION
**Pull request by aselimc**
Hello everyone, 

This PR aims to add new SLAM tool [Continual SLAM](http://continual-slam.cs.uni-freiburg.de/), original repository can be found [here](https://github.com/robot-learning-freiburg/CL-SLAM).

### CODE REVIEW

**Comment by aselimc** [comment]
We have a quick question here to the repository owners. We are using [g2o](https://github.com/RainerKuemmerle/g2o), for optimization; however, there is no setup.py for it. Thus, the installation process is a not straightforward. Here, should I try to write a setup.py file to do this installation automatically, or leave it out and just write how it should be done in README, or what would be your suggestion?

Thanks in advance

**Comment by stefaniapedrazzi** [comment]
> We have a quick question here to the repository owners. We are using [g2o](https://github.com/RainerKuemmerle/g2o), for optimization; however, there is no setup.py for it. Thus, the installation process is a not straightforward. Here, should I try to write a setup.py file to do this installation automatically, or leave it out and just write how it should be done in README, or what would be your suggestion?
> 
> Thanks in advance

Yes, you should write a `setup.py` file.
We should aim at having a script that automatically installs all the tool's dependencies.

**Comment by aselimc** [comment]
@stefaniapedrazzi Hello, I have fixed the setup issue, and now it installs everything automatically. Can you please review the code?

Thanks

**Comment by vniclas** [comment]
Hi, following up on the email after the meeting. This PR has been ready for review since the last commit.

**Review by omichel — APPROVED** [review]
Thank you.
That looks good to me.

**Comment by passalis** [comment]
Thank you! Can you please update the dependencies to make sure that follow the rest of the toolkit. Currently we are using 
```
torch==1.13.1
torchvision==0.14.1
```
You are specifying `torch==1.9.0`, but since we are having another version only one of the two is going to be installed, either breaking this tool or some of the rest of the tools.

Also, when not absolutely necessary, please consider using less strict versions, allowing for updates, i.e.,`>=` instead of `==` in dependencies.

**Comment by aselimc** [comment]
Hello @passalis , we have addressed everything. Please have a look at the draft again, thank you!

**Review by passalis — APPROVED** [review]
Thank you! @tsampazk @omichel Please also check this one! Thank you!

**Comment by vniclas** [comment]
@passalis @omichel Thank you for the approval!

**Pull request merged**
