### PR TITLE
Merge `develop` into `master`

### PR DESCRIPTION
**Pull request by ad-daniel**
No conflicts.
I've also adapted the branch arguments (of docker files) to point to master in this branch

### CODE REVIEW

**Comment by tsampazk** [comment]
Maybe we can make a last minute addition on the changelog regarding ROS2 as it is a sizeable addition? I entirely forgot about it in the relevant PR, sorry. Also, maybe a general entry about the several bugfixes in the ROS1 nodes?

**Comment by ad-daniel** [comment]
Yes definitely a good idea, can't at the moment, may I ask you to?

**Comment by ad-daniel** [comment]
I've quickly gone through it again and seems fine. After merging this, we can trigger the new packages/docker images and quickly check those work as intended as well

**Comment by tsampazk** [comment]
Thanks Daniel, once again you beat me to it! :laughing:

**Review by tsampazk — APPROVED** [review]

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
