### PR TITLE
Fix copyright dates and double-check rights owner (action required)

### PR DESCRIPTION
**Pull request by ad-daniel**
**Description**
This PR updates the copyright date and enforces the same rights holder (`OpenDR European Project`). Some said nothing, others just OpenDR. 
There were some attributions where the copyright holder was marked as the partner itself, for which I need a confirmation from the relevant partner to know if that contribution was made within the OpenDR context and therefore can simply be renamed as such or if those files should be instead added as exception. 

I didn't tag everyone, so if you see somebody missing please tag anybody that is relevant.

Changes requiring validation (**put a checkmark if the change done is validated**):

**Aarhus University:** @iliiliiliili

As it is part of the demo, I assumed they were done in the context of OpenDR so I changed the rights holder from `Aarhus University` to `OpenDR`. Can you validate the change? Or should it be reverted and an exception added?

- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/data_generators.py
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/draw_point_clouds.py 
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/metrics.py 
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/o3m_lidar/channel.py
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/o3m_lidar/main.py
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/o3m_lidar/o3m_lidar.py
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/o3m_lidar/structures.py
- [x] projects/perception/object_detection_3d/demos/voxel_object_detection_3d/rplidar_processor.py

**Aristotle University of Thessaloniki:** @passalis @Pavlos-Tosidis 

For the most part they appear (correct me if I'm wrong) to be contibutions to the OpenDR framework, so I changed from `Aristotle University of Thessaloniki` to `OpenDR`. Can you validate the change? Or should it be reverted and an exception added?

- [x] projects/simulation/human_dataset_generation/background.py
- [x] projects/simulation/human_dataset_generation/create_background_images.py
- [x] projects/simulation/human_dataset_generation/create_dataset.py
- [x] projects/simulation/human_dataset_generation/data_generator.py
- [x] projects/simulation/human_dataset_generation/reformat_cityscapes.py
- [x] src/opendr/engine/constants.py
- [x] src/opendr/engine/data.py
- [x] src/opendr/engine/datasets.py
- [x] src/opendr/engine/example_learner.py
- [x] src/opendr/engine/learners.py
- [x] src/opendr/engine/target.py
- [x] src/opendr/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_learner.py (@iliiliiliili  probably wrong header)

**Delft University of Technology:**
@jelledouwe 
Files in these folders are attributed to Facebook, with some mentioning minor modifications from OpenDR, so I've added an exception to the `test_license` for these folders (i.e I didn't change the license attribution currently provided). From you I just need to double check everything is coherent copyright wise, or if some should be changed based on whether they are your original contribution instead.

- [x] 'src/opendr/perception/object_detection_2d/gem/algorithm',
- [x] 'src/opendr/perception/object_detection_2d/detr/algorithm',

**Tampere University:** 
@anton-muravev @JenniRaitoharju 

Files in these folders are attributed to `Tampere University`. Since they are in the `algorithm` folder I assumed they pre-existed and therefore weren't done in the context of OpenDR. Hence for now I've just added an exception to the `test_license` and maintained Tampere as the rights owner. Am I correct or should they be changed to OpenDR?

- [x] 'src/opendr/perception/speech_recognition/edgespeechnets/algorithm',
- [x] 'src/opendr/perception/speech_recognition/matchboxnet/algorithm',

### CODE REVIEW

**Comment by Pavlos-Tosidis** [comment]
The changes are fine for Aristotle

**Comment by iliiliiliili** [comment]
Thank you, everything looks fine from my side (AU).

**Comment by jelledouwe** [comment]
Thank you, the changes are okay from my side (TUD).

**Comment by anton-muravev** [comment]
@ad-daniel I double-checked and the work in question was all done under OpenDR. The Tampere University attribution is just an oversight. Please go ahead and change the copyright in these files to the OpenDR project.

**Review by Pavlos-Tosidis — APPROVED** [review]
All licenses checked. Ready to be merged

**Comment by ad-daniel** [comment]
Yes, thank you all, the PR can now be reviewed.

**Review by passalis — APPROVED** [review]
Also seems fine to me. Thank you!

**Pull request merged**
