### PR TITLE
Update PyTorch version in install_nvidia.sh

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
In  #431 we updated the module versions but this script was not updated:
* PyTorch from 1.9.0 to 1.13.1
* Torchvision from 0.10.0 to 0.14.1

In this PR, I propose some changes to update the Python modules version but I'm not sure if they will work on the NVIDIA TX2/AGX/NX .

### CODE REVIEW

**Comment by Pavlos-Tosidis** [comment]
Hello Stefania, I am gonna have a look into that and update to the closest version available soon

**Comment by omichel** [comment]
Hi @Pavlos-Tosidis, did you have a chance to look into this?

**Comment by Pavlos-Tosidis** [comment]
Yeah, meant to comment on it on todays TMT meeting.
So, 1.9 is the latest version supported by TX2. 
Unfortunately, even Nvidia stopped maintaining the JetPack for TX2 so we have to keep the current one (Ubuntu 18.04, with everything that this implies, e.g. python3.6.9).  But since the installation on the embedded devices is not the same as the toolkit for Desktop, updating the repo on the docker images to pull the changes made to the master branch and adding a couple of new dependencies worked fine. (At least all scripts under /projects/python). 
The question now is if we want to keep supporting TX2 and keep the current images and just update the repo used whenever we add/update something, or ditch TX2 or make a new image for NX devices, which support newer JetPack versions and update all dependencies to be the same, if applicable, with the Desktop version.

**Comment by omichel** [comment]
In that case, I believe we should drop support for TX2 in the main branch of this repository otherwise we will be blocked with updating PyTorch. Using willing to use the unsupported TX2 may still revert to an older commit on this repo or older images (which we should document).

**Comment by passalis** [comment]
One other possibility would be to keep the installation for tx-2 only for the tools not failing, i.e., keep the script as it is and add a notice with a list of tools that do not work in this platform (unless nothing works in the updated version, so this should be indeed tackled in a different manner).

**Comment by passalis** [comment]
We can keep the current version on TX-2 image, so we can close this for now.

**Pull request closed without merging**
