### PR TITLE
Docker test release

### PR DESCRIPTION
**Pull request by ManosMpampis**
This PR have fixes about docker compilation on PC for CUDA and CPU.
It was made after Issue [Nanodet C api fails on docker](https://github.com/opendr-eu/opendr/issues/414).
It was tested in CUDA 11.2

### CODE REVIEW

**Comment by ManosMpampis** [comment]
@ad-daniel  Can you double check this PR? I have tested with "test release" and docker was build successfully. I whould like to be tested in CUDA from someone else too before merge this PR.

**Review by ad-daniel — APPROVED** [review]
The build process worked for me and appears to be working in the CI as well, I no longer see the compilation error. I don't know how generic the solution you propose is (whether we can always find a libtorch for download based on the CUDA_VERSION determined with this method (seems a bit a hack)), but I think we can proceed this way for now and if problems arise we can either fix them or revert this PR.

The failures in the CI are unrelated

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Comment by ManosMpampis** [comment]
It is ready for review, in the current status the 1.9.0 torch is installing for C implementation. If we want 2 different implementations, one for the embededs and one for the pc, we can first install the runtime dependences and much the version of pytorch in dependences/download_torch.py

**Pull request merged**
