### PR TITLE
Update citation of Seq2Seq-NMS

### PR DESCRIPTION
**Pull request by charsyme**
This PR updates the citation of Seq2Seq-NMS. The methods was previously cited using the preprint version.

### CODE REVIEW

**Comment by charsyme** [comment]
This PR is ready for the review

**Review by stefaniapedrazzi — COMMENTED** [review]
Why did you remove the reference link?
Even if you removed the link to the documentation, it seems to be better to have a link in the text that points to the reference instead of just `[1]` text.

**Comment by charsyme** [comment]
I made the necessary changes, I think it's ok now.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Review by passalis — APPROVED** [review]

**Pull request merged**
