### PR TITLE
Binary High Resolution Learner

### PR DESCRIPTION
**Pull request by passalis**
This PR adds a binary high resolution learner to the toolkit.

Pending tasks:

- [x] Complete Python Implementation
- [x] Add demos
- [x] Add tests
- [x] Add documentation
- [x] Add ROS/ROS2 nodes
- [x] Update changelog

### CODE REVIEW

**Comment by tsampazk** [comment]
Performance evaluation from the docs is currently missing. It might take a while to complete, so i will add it in a follow-up PR.

**Comment by passalis** [comment]
This is ready to review.

**Review by tsampazk — APPROVED** [review]
Looks good from my side, i have already fixed any issues i found before.

**Review by Pavlos-Tosidis — APPROVED** [review]
Seems fine with me!

**Review by tsampazk — DISMISSED** [review]
Resolved conflicts and merged with develop.

**Review by Pavlos-Tosidis — DISMISSED** [review]

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Only minor stuff from my side.

What I gather from the placement is that this tool is meant to be used on it's own, right? If it is meant to be distributed as a wheel then it should be added to `packages.txt`

If the tool is allowed to be installed this way, then I suspect (didn't test) the `dependencies.ini` might be missing a couple of entries. For example `scikit-learn` and `onnx` (onnx, onnxruntime, protobuf). But yea, would be better to test

**Comment by passalis** [comment]
Thanks @ad-daniel, you are right! I included the dependencies and updated the `packages.txt`. I am waiting for the tests to pass.

**Review by ad-daniel — APPROVED** [review]
Appears to be working now, thank you!

**Review by tsampazk — APPROVED** [review]
Thank you @ad-daniel

**Pull request merged**
