### PR TITLE
Facial valence arousal estimation

### PR DESCRIPTION
**Pull request by negarhdr**
This pull request adds the ensemble_based_cnn_learner module for facial valence-arousal estimation and expression recognition. 
The learner is located in: 
`opendr/perception/facial_expression_recognition/ensemble_based_cnn/`

And the demo is located in: 
`opendr/projects/perception/facial_expression_recognition/ensemble_based_cnn
`
The pretrained models and data will be available on FTP server soon, and all the unit tests will be passed then. 

Note: Pretrained models are uploaded on FTP server only for passing the unit tests. After merging the branch, the pretrained models should be removed (out of access for public) because the license of the dataset on which the model is trained does not allow commercial uses. 
I mentioned it in the module's document as well and added the link from which the end-user can download the pretrained weights if necessary.

### CODE REVIEW

**Comment by negarhdr** [comment]
> was the change to eagerx submodule intentional? I think that's why most tests are failing

No, I think it was unintentional! I don't find the changes BTW to rollback!

**Comment by ad-daniel** [comment]
Not sure how it happened either, but for some reason a submodule that was removed a while ago re-appeared partially in this PR. Should be fine now

**Comment by stefaniapedrazzi** [comment]
Are the changes to `audiovisual_emotion_learner` related to this PR?
Are the changes related to `EfficientPS` related to this PR?
If not, they should be removed and the original files should be restored.

It seems that you based your PR on an old branch and many unrelated changes are now included.

I would suggest you to convert this PR to draft until is ready for review.

**Comment by negarhdr** [comment]
> Are the changes to `audiovisual_emotion_learner` related to this PR? Are the changes related to `EfficientPS` related to this PR? If not, they should be removed and the original files should be restored.
> 
> It seems that you based your PR on an old branch and many unrelated changes are now included.
> 
> I would suggest you to convert this PR to draft until is ready for review.

On which branch should I base the PR? I based it on develop branch.

**Comment by stefaniapedrazzi** [comment]
> On which branch should I base the PR? I based it on develop branch.

Yes, this is fine.
But it seems like when creating your branch locally the `develop` branch you used was not the latest one.
This could be an explanation why you have so many unrelated changes that needs to be reverted.
But it could also be that you changes unrelated files on your local repo and then pushed the changes.
However, it is not a problem. You just need to revert them.

**Pull request closed without merging**
