### PR TITLE
ROS1 final updates

### LINKED ISSUE #209: [ROS nodes] Inputs topics options for ROS
In order for the toolkit to be more homogeneous we would need to choose between those two options:

1. Use the input topics as an option to pass to the rosrun like : rosrun perception test.py input_topic:=/input. This option would require to create a roslaunch file where you would need to modify there the input topics.
For example this package is using this method : https://github.com/opendr-eu/opendr/blob/tx2_install/projects/opendr_ws/src/perception/scripts/speech_command_recognition.py

2. Use ROS parameters : Each function will take rosparams as topic input. This option will be to create a config.yaml file once with all the parameters that you would need to set up the ROS params.
For example this package is using this method : https://github.com/opendr-eu/opendr/blob/tx2_install/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py
is using rosparam

For now the ROS nodes in OpenDR are using both of those options. 
The second option would be a bit better.

### LINKED ISSUE #275: ROS nodes delay
### General Description
Some ROS nodes exhibit delay between the current frame and the frame that is being published.

### Cause
This is because in most (all?) nodes the subscriber which uses the callback that performs inference, has a `queue_size` of `10`. If the callback inference is slow, the subscriber keeps the incoming frames and processes them all one-by-one. When processing of one frame ends, the callback grabs an old frame from inside the queue and so on, causing the delay in the output.

### Expected behaviour and solution
The expected behaviour would be to process the newest, most update-to-date frame every time the callback grabs a frame for inference and not use older frames. This is done by setting the `queue_size` to `1`, but to properly work in ROS 1 you also need to set the `buffer_size` accordingly. I found that a value of `5000000` for the buffer size works well on object detection 2D. The delay is minimized to whatever time it takes for one frame to process which is expected.

Edit: ~~Some~~ All nodes require a larger buffer size to minimize delay, e.g. `10000000`.

Edit: **For ROS2 it is not required to set the buffer size, just add `1` as the queue size as seen [here](https://github.com/opendr-eu/opendr/blob/b9dab8c0764143d9817944851defa8502750a146/projects/opendr_ws_2/src/opendr_perception/opendr_perception/face_detection_retinaface_node.py#L53-L63).**

### LINKED ISSUE #303: rosnode - rgbd_hand_gesture_recognition.py - parameter
Parameters need to be consistent with other tools with agparser

I am using opendr installed on my computer on the develop branch, I am feeding the rgb camera topic and the depth_image like this one:
image

I cannot get an output from the /opendr/gestures topic
Is the depth_image topic different from the one that you are using?

### LINKED ISSUE #305: [Tracker] ROS1 nodes updates and dixes
This issue serves to track the progress on the updates on all ROS1 nodes, as per the use-case partner feedback as well as fixes regarding consistency across all nodes. Also, the delay issues mentioned in #275 should be fixed along with the other changes, as well as issue #209 relating to input topics etc.

Main issues to fix:
----

Below there's a list of main issues that need fixing, i tried to check out all the nodes and made some comments in parentheses on what i noticed, so use them to get a general sense on the issues:

1. **Argparse usage** as seen [here](https://github.com/opendr-eu/opendr/blob/develop/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py#L105-L115).
2. **Argument names and default values consistency across nodes**, as seen in [node class ctor](https://github.com/opendr-eu/opendr/blob/develop/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py#L31-L33) and [argparse](https://github.com/opendr-eu/opendr/blob/develop/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py#L105-L115). Arguments especially in argparse which is the interface the users interact with, should have descriptive names like `input_rgb_image_topic` and `input_depth_image_topic`, etc, as well as default values to run out-of-the-box if possible.
3. Updated **device selection** as seen [here](https://github.com/opendr-eu/opendr/blob/develop/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py#L117-L128).
4. Preferably, if the node has multiple outputs, we should provide the option to disable them as seen [here](https://github.com/opendr-eu/opendr/blob/develop/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py#L51-L59), with appropriate changes in the callback too.
5. Make sure you update your docstrings for wrong argument names, typos, some nodes mentioning different tools, etc.
6. Please test whether your node has delay issues as described in #275 and if you need to adjust the queue sizes.
7. Keep in mind the feedback provided by the use-case partners

Tracking list:
----

- [ ] Audiovisual emotion recognition (updates in argparse, device code, device argument, argument naming/default values)
- [ ] Face detection retinaface
- [ ] Face recognition
- [ ] Fall detection
- [ ] Heart anomaly detection (updates in argparse, device code, device argument, docstrings)
- [ ] Landmark-based facial expression recognition (argparse, device code, argument naming/default values, docstrings, `pose_estimation` variables)
- [ ] Object detection 2D - centernet
- [ ] Object detection 2D - detr (some updates in #296, should be good to go)
- [ ] Object detection 2D - gem (argparse, device code, argument naming/default values) (updates in #295)
- [ ] Object detection 2D - ssd
- [ ] Object detection 2D - yolov3
- [ ] Object detection 3D - voxel (argparse, device code, argument naming/default values, docstrings)
- [ ] Object tracking 2D - deep sort (argparse, device code, argument naming/default values)
- [ ] Object tracking 2D - fair mot (argparse, device code, argument naming/default values)
- [ ] Object tracking 3D - ab3dmot (argparse, device code, argument naming/default values, docstrings)
- [ ] Panoptic segmentation efficient ps
- [ ] Pose estimation
- [ ] RGBD hand gesture recognition (argparse, device code, argument naming/default values, docstrings, see #303)
- [ ] Semantic segmentation bisenet
- [ ] Skeleton-based action recognition (argparse, device code, argument naming/default values, see #304)
- [ ] Speech command recognition (updates in argparse, device code, argument naming/default values, docstring)
- [ ] Video activity recognition (argparse, device code, argument naming/default values, docstring, see #302)

### LINKED ISSUE #309: Errors when testing tools
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ALEASC~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/ALEASC~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ALEASC~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DA link=blue vlink="#954F72" style='tab-interval:65.2pt;word-wrap:
break-word'>

List of tools | Object detection and tracking of   humans in the field | Scene understanding | Animal detection | Test output
-- | -- | -- | -- | --
rosrun perception fall_detection.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Output:   [INFO] [1663159449.682438, 167824.240000]: Fall detection node started!
rosrun perception pose_estimation.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Output:   [INFO] [1663159294.174351, 167687.850000]: Pose estimation node started!
rosrun perception object_tracking_2d_fair_mot.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Got this continuous output:   error in modulated_deformable_im2col_cuda: too many resources requested for   launch   error in modulated_deformable_im2col_cuda: too many resources requested for   launch   [INFO] [1663159159.210091, 167569.950000]: Published annotated image   [INFO] [1663159159.214582, 167569.950000]: Published detection boxes   [INFO] [1663159159.218589, 167569.950000]: Published tracking ids
rosrun perception object_tracking_2d_deep_sort.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Can’t find this part
rosrun perception object_detection_2d_ssd.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Detection: Yes/No - Not all scenario is detected.   Speed: 1.28 FPS (output) @ 4.76 FPS (input) - Moving   average size = 400
rosrun perception object_detection_2d_yolov3.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Detection: Yes   Speed: 1.44 FPS (output) @ 4.76 FPS (input) - Moving   average size = 400
rosrun perception object_detection_2d_centernet.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Detection: Yes - Multiple Bbox for 1 object.   Speed: 1.31 FPS (output) @ 4.76 FPS (input) - Moving   average size = 400
rosrun perception object_detection_2d_detr.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Didn’t output anything on the topic.   Last output on cmd:   [INFO] [1663158288.858492, 0.000000]: DETR node started!
rosrun perception semantic_segmentation_bisenet.py   _input_image_topic:=/vision/camera/cropeye3/image_raw |   | x |   | [FATAL] [1663158442.962755]: cannot register subscription topic   [/_input_image_topic:=/vision/camera/cropeye3/image_raw] with master: ERROR:   parameter [topic] contains illegal chars   [ERROR] [1663158442.969023]: Unable to immediately register with master node   [http://192.168.20.100:11311]:   master may not be running yet. Will keep trying.

</body>

</html>

### PR DESCRIPTION
**Pull request by tsampazk**
This PR should conclude the fixes for the ROS1 workspace and packages of OpenDR.

1. Applied some fixes i missed on the previous PR #357 
2. Renamed all ROS1 package directories to include "opendr_" prefix in their names, e.g. "perception"->"opendr_perception" as suggested
3. Renamed references that i could find to the package names in their corresponding package.xml, CMakeLists.txt, etc.
4. READMEs for opendr_perception package will be updated in a separate PR (#316) to include changes from this PR
5. Added "_node" in all node script filenames, to match those in ROS2 (#256). This makes it obvious that these .py files are the ROS nodes
6. Renamed the ros bridge doc file in the documentation to match the package name
7. Found an unrelated issue in `/dependencies/pip_requirements.txt`, where the old version of python was used and brought it up to speed with the main installation script that installs `torch==1.9.0`.

I added a comment [here](https://github.com/opendr-eu/opendr/blob/d11b710f7deec35d84522c8489dfc1c17a099503/projects/opendr_ws/src/opendr_ros_bridge/setup.py#L18) in setup.py of ros bridge, so it shows up in the review. I don't know whether this file is used but the name of the package there seems wrong.

closes #209, closes #275, closes #303, closes #305, closes #309

### CODE REVIEW

**Review by ad-daniel — APPROVED** [review]
No issues from my side, everything built fine. Thank you!

**Review by passalis — APPROVED** [review]
Thank you!

**Comment by tsampazk** [comment]
Added some minor link fixes, etc., in the docs.

Renamed the bridge directories etc to `opendr_bridge` instead of `opendr_ros_bridge`, as the name of the actual package used is `opendr_bridge`. I realised this from Niko's comment in his review.

I kept the docs file name as `opendr-ros-bridge.md` to make it clear among all other docs that this bridge is related to ros, but fixed the package name referred within.

**Review by passalis — APPROVED** [review]

**Comment by ad-daniel** [comment]
> Renamed the bridge directories etc to `opendr_bridge` instead of `opendr_ros_bridge`, as the name of the actual package used is `opendr_bridge`. I realised this from Niko's comment in his review.

so no distinction will be made between ROS and ROS2?

**Comment by tsampazk** [comment]
> > Renamed the bridge directories etc to `opendr_bridge` instead of `opendr_ros_bridge`, as the name of the actual package used is `opendr_bridge`. I realised this from Niko's comment in his review.
> 
> so no distinction will be made between ROS and ROS2?

Do you think that it is needed? Do we expect users to run ROS and ROS2 in parallel and import messages while having source both workspaces? I could rename the ROS2 package to `opendr_bridge_2` similar to how the workspace is named.

**Review by passalis — APPROVED** [review]

**Pull request merged**
