### PR TITLE
2D Object Tracking (Deep SORT)

### PR DESCRIPTION
**Pull request by iliiliiliili**
Added Deep SORT implementation for 2D Object Tracking. This PR is based on the FairMOT implementation, so it should be reviewed after the FairMOT PR.

### CODE REVIEW

**Review by passalis — DISMISSED** [review]
Nice work! Please make sure to provide a few demos in the projects folder for the first version of the toolkit.

**Comment by stefaniapedrazzi** [comment]
I convert this PR to draft.
Please change the status when it is ready for review.

**Comment by stefaniapedrazzi** [comment]
What is the status of this PR?
It seems it is on hold since many months.

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Thank you, I only have a few formatting changes to suggest.
Also I believe it is missing an [example](https://github.com/tasostefas/opendr_internal/wiki/Adding-New-Tool#example) (I think) and linking the added documentation in the `index.md` file

**Pull request merged**
