### PR TITLE
Image-based facial emotion estimation ROS2 node

### PR DESCRIPTION
**Pull request by negarhdr**
This branch adds ROS2 node for the image_based facial emotion estimation tool.

### CODE REVIEW

**Comment by negarhdr** [comment]
This node is for the image_based_facial_emotion_estimation tool which is not integrated yet. The PR for that tool (which is still open) merges branch "fer_va_estimation" to "develop".

**Comment by tsampazk** [comment]
I think it might be better to convert this to draft for now and wait for the tool to be merged first, so we can also test it.

**Comment by tsampazk** [comment]
Thanks Negar, i actually forgot about the ROS2 node, i'll go ahead and test it and apply any changes that might be needed.

**Comment by negarhdr** [comment]
> Thanks Negar, i actually forgot about the ROS2 node, i'll go ahead and test it and apply any changes that might be needed.

Thank you. I think it can be tested when the fer_va_estimation tool is merged. Because this branch is based on the ros2 branch.

**Comment by tsampazk** [comment]
I will do it locally :)

**Comment by tsampazk** [comment]
Node should be good to go as soon as #264 is merged. :smile:

**Pull request merged**
