### PR TITLE
Human model gen scikit fix

### PR DESCRIPTION
**Pull request by charsyme**

### CODE REVIEW

**Comment by tsampazk** [comment]
I think it's better to target develop for the merge, and i also added the test-release tag as the tests failed on the docker tests.

**Review by tsampazk — APPROVED** [review]
Thanks @charsyme, fixes are good. The tests failed on yolov5 with an HTTP error stating rate limit exceed so i re-run it. Hopefully it will pass.

**Comment by ad-daniel** [comment]
I'm confused, so [leaving](https://github.com/opendr-eu/opendr/blob/58a906752250a385f1c7195914670ab0b6bb63de/src/opendr/simulation/human_model_generation/dependencies.ini#L10) it as it was before still fixed this issue https://github.com/opendr-eu/opendr/issues/334? Your comment says it should be `scikit-image==0.17.2` but it doesn't seem you made the change in the ini. It should be noted that panoptic segmentation imposes 0.18.1 [here](https://github.com/DeepSceneSeg/EfficientPS/blob/d03deab54edc5da15ed63318b3d1b14fb9712441/environment.yml#L71), so there might be a conflict with that if these 2 tools are installed together

**Comment by charsyme** [comment]
@ad-daniel I installed the develop and the ros2 branches, and installed scikit-image==0.17.2 (my limitation was scikit-image>0.16.2). I am not sure why panoptic segmentation didn't installed the 0.18.1 version. I will test until tomorrow the human model generation module with 0.18.1 version again and provide a confirmation that it still works. However, I am positive that newer version (>0.19) may cause problems to the tool so I may provide a limit for those newer versions >=0.19.

**Comment by ad-daniel** [comment]
is 0.17.2 already being enforced in the ros2 branch? can we close this?

**Comment by charsyme** [comment]
@ad-daniel the PR contains changes to ros files of the module. Should those changes be merged.

[human_model_generation_client.py](https://github.com/opendr-eu/opendr/pull/377/commits/672e34cdf68bbc3e2087981a2022db2bf5d87876)

[Update human_model_generation_service.py](https://github.com/opendr-eu/opendr/pull/377/commits/f9b255cce3c62f540c3bf3b94a00e22641ae719c)

**Comment by tsampazk** [comment]
I think we should go ahead and merge these fixes even if they are unrelated.

**Review by tsampazk — APPROVED** [review]

**Review by ad-daniel — APPROVED** [review]
Thank you

**Pull request merged**
