### PR TITLE
ROS1 and ROS2 nodes for CoSTGCN

### PR DESCRIPTION
**Pull request by negarhdr**
This PR adds ROS1 and ROS2 nodes for the continual skeleton-based action recognition tool (continual_stgcn_learner).

### CODE REVIEW

**Review by tsampazk — CHANGES_REQUESTED** [review]
I fixed several minor things for the nodes, applied a minor fix in the learner to be able to load weights from .pt files and added ROS documentation entries.

The nodes give the following errors:
```
File "/opendr/projects/opendr_ws/src/opendr_perception/scripts/continual_skeleton_based_action_recognition.py", line 149, in callback
    result = self.action_classifier.infer(skeleton_seq)  # input_size: BxCxTxVxS
  File "/opendr/src/opendr/perception/skeleton_based_action_recognition/continual_stgcn_learner.py", line 281, in infer
    batch = batch.to(device=self.device, dtype=torch.float)
AttributeError: 'numpy.ndarray' object has no attribute 'to'
```

It seems that the nodes expect tensors as input for their infer function (as a minor note this is a bit unusual for OpenDR learners). Please fix it in the best way you see fit and let me know when i can test it again.

**Comment by negarhdr** [comment]
> I fixed several minor things for the nodes, applied a minor fix in the learner to be able to load weights from .pt files and added ROS documentation entries.
> 
> The nodes give the following errors:
> 
> ```
> File "/opendr/projects/opendr_ws/src/opendr_perception/scripts/continual_skeleton_based_action_recognition.py", line 149, in callback
>     result = self.action_classifier.infer(skeleton_seq)  # input_size: BxCxTxVxS
>   File "/opendr/src/opendr/perception/skeleton_based_action_recognition/continual_stgcn_learner.py", line 281, in infer
>     batch = batch.to(device=self.device, dtype=torch.float)
> AttributeError: 'numpy.ndarray' object has no attribute 'to'
> ```
> 
> It seems that the nodes expect tensors as input for their infer function (as a minor note this is a bit unusual for OpenDR learners). Please fix it in the best way you see fit and let me know when i can test it again.

Thank you Kostas,
The learner.infer is now receiving a tensor as input. It should work now.

**Comment by tsampazk** [comment]
Just tested the ROS1 node and i get the following:

```
Some model weight could not be loaded: {'layers.layer10.0.1.gcn.A', 'layers.layer9.0.1.gcn.A', 'layers.layer1.gcn.A', 'layers.layer4.0.1.gcn.A', 'layers.layer8.0.1.gcn.A', 'layers.layer7.0.1.gcn.A', 'layers.layer6.0.1.gcn.A', 'layers.layer2.0.1.gcn.A', 'layers.layer3.0.1.gcn.A', 'layers.layer5.0.1.gcn.A'}
[INFO] [1674477712.362296]: Continual skeleton-based action recognition node started.
Warming model up prior to inference
[ERROR] [1674477721.087484]: bad callback: <bound method CoSkeletonActionRecognitionNode.callback of <__main__.CoSkeletonActionRecognitionNode object at 0x7f32b3e92e80>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opendr/projects/opendr_ws/src/opendr_perception/scripts/continual_skeleton_based_action_recognition_node.py", line 150, in callback
    result = self.action_classifier.infer(skeleton_seq)  # input_size: BxCxTxVxS
  File "/opendr/src/opendr/perception/skeleton_based_action_recognition/continual_stgcn_learner.py", line 306, in infer
    results = [
  File "/opendr/src/opendr/perception/skeleton_based_action_recognition/continual_stgcn_learner.py", line 307, in <listcomp>
    Category(prediction=int(r.argmax(dim=0)), confidence=F.softmax(r, dim=-1))
ValueError: only one element tensors can be converted to Python scalars
```

The error repeats until the GPU runs our of memory.

**Comment by negarhdr** [comment]
@LukasHedegaard Apparently the graph adjacency matrix in the pre-trained model does not match the implementation. Can you check the mismatch?

**Comment by LukasHedegaard** [comment]
The "Some model weight could not be loaded" message isn't an error (but it's maybe a bit verbose). The ".A" weights are adjacency matrices, which are defined from the skeleton structure, i.e. the model argument "graph_type". I've committed an update to skip the unnecessary check.

**Comment by LukasHedegaard** [comment]
Rather, it seems that the error happens in the int conversion in the line "Category(prediction=int(r.argmax(dim=0)), confidence=F.softmax(r, dim=-1))". Could we get a print-out of the `batch` and `results` shapes in the `infer` function, @negarhdr ?

**Comment by LukasHedegaard** [comment]
Thanks for checking, @tsampazk . The issue was with `_pose2numpy` which generated four frames instead of one. I've pushed a fix. Let me know if it you encounter further issues.

**Comment by tsampazk** [comment]
> Thanks for checking, @tsampazk . The issue was with `_pose2numpy` which generated four frames instead of one. I've pushed a fix. Let me know if it you encounter further issues.

The previous issue is indeed fixed, thank you. However, my local GPU runs out of memory (4GB) really fast :laughing: Running it on CPU with lots of memory available (32GB), it seems to start publishing detection ids and confidence on the detection topic, but the detection description is not published and i get the error below which seems to indicate something wrong [in the data conversion in the bridge method](https://github.com/opendr-eu/opendr/blob/cebc0b302b2a600a234ffb6e336d55b6ad57422d/projects/opendr_ws/src/opendr_bridge/src/opendr_bridge/bridge.py#L144). I added a print there and wrapped it in str() `result.data = str(category.description)` and the error stopped, but it seems that the description is `None`, regardless of the id and confidence that gets published on the other topic.

Moreover, initially i thought that it hang on the warming up stage, i let it run for quite some time and noticed that the longer it ran the higher the memory usage. The system started at 8.5 GB idle and reached ~30GB after several minutes.

```
[ERROR] [1675250939.722648]: bad callback: <bound method CoSkeletonActionRecognitionNode.callback of <__main__.CoSkeletonActionRecognitionNode object at 0x7fa7402bffd0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_String.py", line 54, in serialize
    length = len(_x)
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_String.py", line 60, in serialize
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 393, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 285, in check_type
    raise SerializationError('field %s must be of type bytes or an ascii string' % field_name)
genpy.message.SerializationError: field data must be of type bytes or an ascii string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opendr/projects/opendr_ws/install/lib/opendr_perception/continual_skeleton_based_action_recognition_node.py", line 158, in callback
    self.string_publisher.publish(self.bridge.to_ros_category_description(category))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field data must be of type bytes or an ascii string

```

**Comment by LukasHedegaard** [comment]
Thank you @tsampazk for being a huge help in testing the ROS node. I've wrapped the infer forward in a torch.no_grad in the hopes that this should fix the memory issues. 

The missing descriptions have been added in a separate commit.

**Review by tsampazk — DISMISSED** [review]
I tested the ROS2 node and as expected it needed the same fix for pose2numpy which i applied along with some other minor fixes. Both nodes run smoothly and look good to go from my side, thank you both!

**Comment by LukasHedegaard** [comment]
> I tested the ROS2 node and as expected it needed the same fix for pose2numpy which i applied along with some other minor fixes. Both nodes run smoothly and look good to go from my side, thank you both!

Great! Thanks for following through, @tsampazk 🙏

**Review by ad-daniel — APPROVED** [review]
thank you!

**Review by tsampazk — APPROVED** [review]

**Pull request merged**
