### PR TITLE
Integration of heart anomaly detection self-attention neural bag of features 

### PR DESCRIPTION
**Pull request by katerynaCh**
This PR integrates  a module for heart anomaly detection as described in [Self-Attention Neural Bag of Features](https://arxiv.org/abs/2201.11092)

### CODE REVIEW

**Review by passalis — CHANGES_REQUESTED** [review]
Thank you! Overall seems fine. Should we also appropriately modify the tests in order to test the new functionality?

**Comment by katerynaCh** [comment]
> Thank you! Overall seems fine. Should we also appropriately modify the tests in order to test the new functionality?

Hi, I have updated the tests accordingly

**Review by omichel — APPROVED** [review]
It looks good to me.

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
