### PR TITLE
Merge master into develop

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Synchonize branches.

### CODE REVIEW

**Review by omichel — DISMISSED** [review]

**Comment by tsampazk** [comment]
@omichel, @passalis  can you check if this is ok? I tried to mimic the workflow of what Stefania did earlier, so we can go ahead and synchronize the branches and continue working on develop.

**Comment by omichel** [comment]
It seems good to me. However, the test-tools (ubuntu-20.04, perception/object_detection_2d/nms) is failing. I restarted it but it failed again...

**Comment by tsampazk** [comment]
> It seems good to me. However, the test-tools (ubuntu-20.04, perception/object_detection_2d/nms) is failing. I restarted it but it failed again...

Nms is expected to fail as described by Charis [here](https://github.com/opendr-eu/opendr/pull/454#issuecomment-1691115894), so we can safely ignore it.

**Review by omichel — APPROVED** [review]
All right, thank you.

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
