### PR TITLE
Update GPU and Docker-GPU installation.md

### PR DESCRIPTION
**Pull request by JVPC0D3R**
#  Update Torchvision Version and Docker CUDA Tag in Installation Docs

## Changes

- Changed the `torchvision` installation command to include `cu116` to ensure compatibility with CUDA 11.6.
- Updated the Docker run commands to use the most recent CUDA tag available on the OpenDR toolkit Docker Hub, `cuda_nightly_290823`, ensuring users have access to the latest features and fixes.

## Justification

- The update to `torchvision` is critical as it provides the necessary binaries compatible with  CUDA 11.6 setup. 
- The Docker tag update is in response to the latest available version which may include important updates and optimizations for CUDA users.

These updates ensure that the installation guide remains current.

### CODE REVIEW

**Comment by passalis** [comment]
Hi, thanks for the suggestions. The most recent versions of docker images are tagged with `v3.0.0`, since this is the latest release. We briefly used nightly tags, but no longer use them. Therefore, `nightly_290823` is older compared to `v3.0.0`.

The actual issue here is that `cuda_v3.0.0` is missing... I will fix this within the day probably.

**Comment by passalis** [comment]
The image was correctly built, but for some reason never pushed successfully to the online repo.  The updated one should be available in a few minutes (it is uploading). Please revert this change in order to proceed with the `torchvision` tag update. Please also target the `develop` branch.

**Review by passalis — DISMISSED** [review]
Thanks.

**Comment by JVPC0D3R** [comment]
I'm excited to collaborate on this project! Thank you @passalis

**Comment by passalis** [comment]
Thanks! I am going to fix the error in another branch (it is related to outdated copyright strings) and then you can go ahead and merge this.

**Review by passalis — APPROVED** [review]

**Pull request merged**
