### PR TITLE
ROS1 updates and fixes for several nodes

### LINKED ISSUE #209: [ROS nodes] Inputs topics options for ROS
In order for the toolkit to be more homogeneous we would need to choose between those two options:

1. Use the input topics as an option to pass to the rosrun like : rosrun perception test.py input_topic:=/input. This option would require to create a roslaunch file where you would need to modify there the input topics.
For example this package is using this method : https://github.com/opendr-eu/opendr/blob/tx2_install/projects/opendr_ws/src/perception/scripts/speech_command_recognition.py

2. Use ROS parameters : Each function will take rosparams as topic input. This option will be to create a config.yaml file once with all the parameters that you would need to set up the ROS params.
For example this package is using this method : https://github.com/opendr-eu/opendr/blob/tx2_install/projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py
is using rosparam

For now the ROS nodes in OpenDR are using both of those options. 
The second option would be a bit better.

### PR DESCRIPTION
**Pull request by tsampazk**
This PR fixes or partially fixes #209 and #275, consistency updates, node arguments, documentation enhancements, and fixes for the following **ROS1** nodes:

- [x] Pose estimation
- [x] Fall detection
- [x] Object Detection 2D Centernet
- [x] Object Detection 2D DETR
- [x] Object Detection 2D SSD
- [x] Object Detection 2D YOLOV3
- [x] Re-check integer type issue
- [x] Face detection retinaface
- [x] Semantic segmentation update
- [x] Face Recognition
- [x] Semantic segmentation enhancements: separated output heatmap from visualization heatmap, improved colors and added legend
- [x] New custom ROS pose message and bridge methods

Edit: This PR should also fix ~~(will be re-checked)~~ :white_check_mark:  the integer type issue (with commits https://github.com/opendr-eu/opendr/pull/281/commits/c7df07bba71b40b8701e73eaa4b66995f9cb0e31 and https://github.com/opendr-eu/opendr/pull/281/commits/4c680cc2ca6b87a2f8b7f741d48927fa5a98e56d) on the bridge method being used by ssd, yolov3, centernet object detection 2d nodes.

### CODE REVIEW

**Comment by tsampazk** [comment]
All nodes mentioned in the PR's description should now have consistent argparse interface in terms of naming and usage, as well as fixed delay to what is described in #275. Also some minor fixes are included. 

Note that in case of testing, semantic segmentation bisenet node depends on [this change](https://github.com/opendr-eu/opendr/commit/19aa6027bab41d8e3b6f9a2a64dcbbe8c415feb8) made in another PR (#269) and should be working when both PRs are merged.

**Comment by tsampazk** [comment]
Added some last minute changes, including ROS pose estimation now using a more useful custom ROS message as per partner feedback, updates to the bridge methods for the new pose messages.

As far as i can tell these are the only custom ROS messages used by the toolkit currently, i took the liberty of adding the new messages to ros_bridge.

**Comment by tsampazk** [comment]
> Everything seems fine to me!
> 
> I just have two very minor comments about indentation.

Thanks @stefaniapedrazzi, i commited the suggested changes.

**Review by stefaniapedrazzi — APPROVED** [review]

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
